source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg', '~> 0.18.1'
gem 'sass-rails', '~> 5.0.1'
gem 'uglifier', '~> 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'slim', '~> 3.0.3'
gem 'jquery-rails', '~> 4.0.3'
gem 'spring', '~> 1.3.3'
gem 'ruby-trello', '~> 1.1.3'
gem 'axlsx', '~> 2.0.1'
gem 'axlsx_rails', '~> 0.3.0'
gem 'dotenv-rails', '~> 2.0.0'
gem 'font-awesome-rails', '~> 4.3.0.0'
gem 'jquery-ui-rails', '~> 5.0.3'
gem 'rails_12factor', group: :production
